name: erni_clean
version: 1.0.0+1
description: Agenda de citas para ErniClean

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.5
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  table_calendar: ^3.0.9
  provider: ^6.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 